/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Controle;


import Conexao.Conexao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
 
public class Design2 extends javax.swing.JFrame {
    Conexao con_cliente;
    /**
     * Creates new form Design2
     */
    public Design2() {
        initComponents();
        con_cliente = new Conexao();
        con_cliente.conecta();//chama o metodo usado para conectar
        con_cliente.executaSQL("select * from tbclientes order by cod");
        preencherTabela();
        posicionarRegistro();
        tblClientes.setAutoCreateRowSorter(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoCodigo = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        campoData = new javax.swing.JTextField();
        campoTelefone = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        PrimeiroRegistro = new javax.swing.JButton();
        VoltarRegistro = new javax.swing.JButton();
        AvancarRegistro = new javax.swing.JButton();
        UltimoRegistr = new javax.swing.JButton();
        NovoRegistro = new javax.swing.JButton();
        Cadastrar = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Pesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CampoCodigo.setText("jTextField1");

        campoNome.setText("jTextField2");

        campoData.setText("jTextField3");

        campoTelefone.setText("jTextField4");

        campoEmail.setText("jTextField5");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Código:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Data nascimento:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Telefone:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Email:");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Data Nascimento", "Telefone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        tblClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblClientesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        PrimeiroRegistro.setIcon(new javax.swing.ImageIcon("D:\\ETEC\\DS\\Atividade\\TesteProjeto\\Primeiro.png")); // NOI18N
        PrimeiroRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimeiroRegistroActionPerformed(evt);
            }
        });

        VoltarRegistro.setIcon(new javax.swing.ImageIcon("D:\\ETEC\\DS\\Atividade\\TesteProjeto\\Voltar.png")); // NOI18N
        VoltarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarRegistroActionPerformed(evt);
            }
        });

        AvancarRegistro.setIcon(new javax.swing.ImageIcon("D:\\ETEC\\DS\\Atividade\\TesteProjeto\\avancar.png")); // NOI18N
        AvancarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvancarRegistroActionPerformed(evt);
            }
        });

        UltimoRegistr.setIcon(new javax.swing.ImageIcon("D:\\ETEC\\DS\\Atividade\\TesteProjeto\\Ultimo.png")); // NOI18N
        UltimoRegistr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltimoRegistrActionPerformed(evt);
            }
        });

        NovoRegistro.setIcon(new javax.swing.ImageIcon("D:\\ETEC\\DS\\Atividade\\TesteProjeto\\novo (2).png")); // NOI18N
        NovoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoRegistroActionPerformed(evt);
            }
        });

        Cadastrar.setIcon(new javax.swing.ImageIcon("D:\\ETEC\\DS\\Atividade\\TesteProjeto\\salvar.png")); // NOI18N
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        Alterar.setIcon(new javax.swing.ImageIcon("D:\\ETEC\\DS\\Atividade\\TesteProjeto\\renomear.png")); // NOI18N
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        Excluir.setIcon(new javax.swing.ImageIcon("D:\\ETEC\\DS\\Atividade\\TesteProjeto\\excluir (1).png")); // NOI18N
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        jLabel6.setText("Pesquisa por nome do usuario:");

        Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PrimeiroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VoltarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AvancarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UltimoRegistr, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel5))
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NovoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel6)
                .addGap(37, 37, 37)
                .addComponent(Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrimeiroRegistro)
                            .addComponent(AvancarRegistro)
                            .addComponent(VoltarRegistro)
                            .addComponent(UltimoRegistr)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cadastrar)
                                    .addComponent(NovoRegistro))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Alterar)
                                    .addComponent(Excluir)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CampoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblClientesKeyPressed
        int linha_selecionada = tblClientes.getSelectedRow();
        CampoCodigo.setText(tblClientes.getValueAt(linha_selecionada, 0).toString());
        campoNome.setText(tblClientes.getValueAt(linha_selecionada, 1).toString());
        campoData.setText(tblClientes.getValueAt(linha_selecionada, 2).toString());
        campoTelefone.setText(tblClientes.getValueAt(linha_selecionada, 3).toString());
        campoEmail.setText(tblClientes.getValueAt(linha_selecionada, 4).toString());




    }//GEN-LAST:event_tblClientesKeyPressed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        int linha_selecionada = tblClientes.getSelectedRow();
        CampoCodigo.setText(tblClientes.getValueAt(linha_selecionada, 0).toString());
        campoNome.setText(tblClientes.getValueAt(linha_selecionada, 1).toString());
        campoData.setText(tblClientes.getValueAt(linha_selecionada, 2).toString());
        campoTelefone.setText(tblClientes.getValueAt(linha_selecionada, 3).toString());
        campoEmail.setText(tblClientes.getValueAt(linha_selecionada, 4).toString());


    }//GEN-LAST:event_tblClientesMouseClicked

    private void AvancarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvancarRegistroActionPerformed
        try{
            con_cliente.resultset.next();
            mostrar_dados();
        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o próximo registro!:(" +erro, "Mensagem do progama", JOptionPane.INFORMATION_MESSAGE);
           
        }
                 


    }//GEN-LAST:event_AvancarRegistroActionPerformed

    private void PrimeiroRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimeiroRegistroActionPerformed
        try{
            con_cliente.resultset.first();
            mostrar_dados();
        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o primeiro registro!:(" +erro, "Mensagem do progama", JOptionPane.INFORMATION_MESSAGE);
           
        }
    }//GEN-LAST:event_PrimeiroRegistroActionPerformed

    private void VoltarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarRegistroActionPerformed
 try{
            con_cliente.resultset.previous();
            mostrar_dados();
        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o registro anterior!:(" +erro, "Mensagem do progama", JOptionPane.INFORMATION_MESSAGE);
           
        }
          



    }//GEN-LAST:event_VoltarRegistroActionPerformed

    private void UltimoRegistrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltimoRegistrActionPerformed
try{
            con_cliente.resultset.last();
            mostrar_dados();
        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível acessar o último registro!:(" +erro, "Mensagem do progama", JOptionPane.INFORMATION_MESSAGE);
           
        }
                   


    }//GEN-LAST:event_UltimoRegistrActionPerformed

    private void NovoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoRegistroActionPerformed
        CampoCodigo.setText("");
        campoNome.setText("");
        campoData.setText("");
        campoTelefone.setText("");
        campoEmail.setText("");
        CampoCodigo.requestFocus();//posiciona o cursor no campo para que digitem



    }//GEN-LAST:event_NovoRegistroActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        String nome= campoNome.getText();
        String data= campoData.getText();
        String telefone= campoTelefone.getText();
        String email= campoEmail.getText();

        try {
String insert_sql = "INSERT INTO tbclientes (nome, telefone, email, dt_nasc) VALUES ('" + nome + "', '" + telefone + "', '" + email + "', '" + data + "')";
            con_cliente.statement.executeUpdate(insert_sql);//executa o comando de inserção
            JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso!!" , "Mensagem do Progama", JOptionPane.INFORMATION_MESSAGE);
            con_cliente.executaSQL("select * from tbclientes order by cod");
            con_cliente.resultset.first();
            preencherTabela();
            mostrar_dados();//mostra os dados nas caixas de texto
        }
        catch(SQLException errosql){
            JOptionPane.showMessageDialog(null, "\n Erro na gravação :n "+errosql, "Mensagem do Progama", JOptionPane.INFORMATION_MESSAGE );
        }
    }//GEN-LAST:event_CadastrarActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
            String nome= campoNome.getText();
            String data= campoData.getText();
            String telefone= campoTelefone.getText();
            String email= campoEmail.getText();
            String sql = "";
            String msg="";
            
            try{
                if(CampoCodigo.getText().equals((""))){//caso o user nao digite nada na caixa de texto será feito inclusão e não alteração
                    sql = "INSERT INTO tbclientes (nome, telefone, email, dt_nasc) VALUES ('" 
                + nome + "', '" + telefone + "', '" + email + "', '" + data + "')";                   msg= "Gravação de um novo registro"; 
                }
                else{
            sql = "UPDATE tbclientes SET nome = '" + nome + "', telefone = '" + telefone + "', email = '" + email + "', dt_nasc = '" + data + "' WHERE cod = " + CampoCodigo.getText();
                    msg= "Alteração de registro";
                }
                
                con_cliente.statement.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, msg+ " realizada com sucessoo!!:)", "Mensagem do Progama", JOptionPane.INFORMATION_MESSAGE);
           
                con_cliente.executaSQL("select * from tbclientes order by cod");
                con_cliente.resultset.first();
                preencherTabela();
                mostrar_dados();
            }
          
            catch(SQLException errosql){
                JOptionPane.showMessageDialog(null, "\n Erro na gravação :\n "+errosql, "Mensagem do Progama" , JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_AlterarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
            String sql = "";
           
            try{
                int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro: ", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION,3);
              
                if (resposta==0){
                    sql = "delete from tbclientes where cod = " + CampoCodigo.getText();
                    int excluir = con_cliente.statement.executeUpdate(sql);
                   
                    if(excluir==1){
                        JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!!", "Mensagem do Progama", JOptionPane.INFORMATION_MESSAGE);
                        con_cliente.executaSQL("select * from tbclientes order by cod");
                        con_cliente.resultset.first();
                        preencherTabela();
                        posicionarRegistro();
                    
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Operação cancelada pelo usuario!!", "Mensagem do Progama", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                  } 
                catch(SQLException excecao){
                        JOptionPane.showMessageDialog(null, "Erro na exclusão: "+excecao, "Mensagem do Progama", JOptionPane.INFORMATION_MESSAGE);
                        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisaActionPerformed
        try{
            String pesquisa = "select * from tbclientes where nome like '" + Pesquisa.getText() + "%'";
        con_cliente.executaSQL(pesquisa);
        
        if(con_cliente.resultset.first()){
            preencherTabela();
        }
        else{
            JOptionPane.showMessageDialog(null, "\n Não existem dados com este paramêtro!!", "Mensagem do Progama", JOptionPane.INFORMATION_MESSAGE);
        }
 }
        catch(SQLException errosql){
            JOptionPane.showMessageDialog(null, "\n Os dados digitados não foram localizados!!:\n" +errosql, "Mensagem do Progama", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_PesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void preencherTabela(){
        tblClientes.getColumnModel().getColumn(0).setPreferredWidth(4);
        tblClientes.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblClientes.getColumnModel().getColumn(2).setPreferredWidth(11);
        tblClientes.getColumnModel().getColumn(3).setPreferredWidth(14);
        tblClientes.getColumnModel().getColumn(4).setPreferredWidth(100);
        
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
        modelo.setNumRows(0);
        
        try{
            con_cliente.resultset.beforeFirst();
            while(con_cliente.resultset.next()){
                    modelo.addRow(new Object []{
                        con_cliente.resultset.getString("cod"), con_cliente.resultset.getString("nome"), con_cliente.resultset.getString("dt_nasc"), con_cliente.resultset.getString("telefone"), con_cliente.resultset.getString("email")
            });
            }
        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "\n Erro ao listar dados da tabela!!:\n" +erro, "Mensagem do progama", JOptionPane.INFORMATION_MESSAGE);
        }}
        
    public void posicionarRegistro(){
        try{
            con_cliente.resultset.first();
            mostrar_dados();
        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no pirimeiro registro: "+erro, "Mensagem do Progama", JOptionPane.INFORMATION_MESSAGE);
        }}
    
    public void mostrar_dados(){
        try{
                CampoCodigo.setText(con_cliente.resultset.getString("cod"));//associa a caixa de texto ao campo codigo
                campoNome.setText(con_cliente.resultset.getString("nome"));
                campoData.setText(con_cliente.resultset.getString("dt_nasc"));
                campoTelefone.setText(con_cliente.resultset.getString("telefone"));
                campoEmail.setText(con_cliente.resultset.getString("email"));

        }
        catch(SQLException erro){
            JOptionPane.showMessageDialog(null, "Não foi possível posicionar no primeiro registro: "+erro,"Mensagem do Progama", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
        
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Design2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Design2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Design2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Design2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Design2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton AvancarRegistro;
    private javax.swing.JButton Cadastrar;
    private javax.swing.JTextField CampoCodigo;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton NovoRegistro;
    private javax.swing.JTextField Pesquisa;
    private javax.swing.JButton PrimeiroRegistro;
    private javax.swing.JButton UltimoRegistr;
    private javax.swing.JButton VoltarRegistro;
    private javax.swing.JTextField campoData;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
